### ISSUE TITLE
Frontend Materialize Styling

### ISSUE THREAD

**Issue by joshacross** [joshacross/final-project#16]
- [x]  Navbar
- [ ]  Global
- [ ]  Home
- [ ]  Import Hero Image on Home
- [ ]  Details Page
- [x]  Modal on Details Page - Reduce QR and Hiro images to fit and make them responsive
- [ ]  Footer
- [ ]  Hover Modals on products (preview)
- [ ]  Login
- [ ]  Logout Success page

**Comment by bsottek** [comment]
Blocked by #26
