### ISSUE TITLE
"All" category button

### ISSUE THREAD

**Issue by bsottek** [joshacross/final-project#22]
Provide button with link to home or no filter

**Comment by JohnBanas** [comment]
Issue resolved in branch feature/all-product-button by created new button outside of the category mapping function in the Category component. The button on click event handler function uses dispatch to reset the currentCategory to an empty string in the global state. Using React context we access that currentCategory global state in the ProductList component. If there is a currentCategory selected, then it will map through the products and show products who have that category _id. If there is no currentCategory selected it shows all products, hence the button click handler in Category setting the currentCategory to an empty string.
