### ISSUE TITLE
Fix Stripe/Checkout

### ISSUE THREAD

**Issue by bsottek** [joshacross/final-project#25]
(Checkout not initiating on click) - original issue comment.
see comment below for new issue.

**Comment by JohnBanas** [comment]
I am not closing this issue because even though at the moment stripe is working, we have test api keys hard-coded. @carrington13 said that we need some sort of saving technology on client side, that was recommended by Stripe.

**Comment by JohnBanas** [comment]
Upon further investigation, the test api keys both secret and public are fine to use for development and are okay being visible in our application, they can not change anything on our accounts and there is no access to card networks or payment providers. Only the **test** payment data from stripe can be used. When deploying to a live integration however, you would need to keep the secret api key in a password manager, or some other sort of secure location.
